name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa todo dia à meia-noite UTC
  workflow_dispatch: # Permite execução manual

jobs:
  generate:
    name: Generate Snake SVG
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: jose-GuilhermeG
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate snake animation"
          add: "dist/*"
